name: ipk

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      device:
        description: 'select device to build'
        default: 'r2s'
        required: false

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - name: build
      run: |
        sudo -E apt-get -y install gcc make && \
        mkdir -p /tmp/po2lmo && \
        wget -qO /tmp/po2lmo/po2lmo.c raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/po2lmo.c --show-progress && \
        wget -qO /tmp/po2lmo/Makefile raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/Makefile --show-progress && \
        wget -qO /tmp/po2lmo/template_lmo.h raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/template_lmo.h --show-progress && \
        wget -qO /tmp/po2lmo/template_lmo.c raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/template_lmo.c --show-progress && \
        cd /tmp/po2lmo && make po2lmo >/dev/null 2>&1 && ./po2lmo $GITHUB_WORKSPACE/luci-app-softwarecenter/po/zh-cn/pp.po /tmp/pp.zh-cn.lmo >/dev/null 2>&1
        cd /tmp
        
    - name: 上传 lmo
      uses: actions/upload-artifact@v3
      with:
        path: /tmp/pp.zh-cn.lmo
        name: lmo
