name: 下载 Cache

on:
  schedule:
    - cron: 0 5 */10 * *
  workflow_dispatch:
jobs:
  build:
    name: 下载 Cache
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 下载 Cache
        continue-on-error: true
        run: wget -qO- git.io/lean_openwrt | cache_Release=true bash

      - name: Cache 上传到 Release
        if: env.UPLOAD_Release == 'true'
        uses: softprops/action-gh-release@master
        with:
          name: Cache
          files: output/*
          tag_name: Cache
          token: ${{secrets.GITHUB_TOKEN}}
