name: uboot-rockchip/rockchip
on:
  workflow_dispatch:
    inputs:
      device:
        description: '运行工作流程'
        default: '运行'
        required: false
      nd:
        description: '下载的数量，默认最新的100个'
        required: false

  release:
    types: [published]

permissions:
  contents: read

jobs:
  build_packages:

    permissions:
      contents: write # for release creation
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: echo
      run: echo

  immortalwrt_rockchip:
    permissions:
      contents: write
    env:
      ND: ${{github.event.inputs.nd}}
    needs: build_packages
    name: immortalwrt-rockchip
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: immortalwrt-rockchip
      id: feeds
      run: |
        mkdir output
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        echo "STRDATE=$(date +%Y-%m-%d)" >>$GITHUB_ENV
        url=(
        https://github.com/immortalwrt/immortalwrt/trunk/target/linux/rockchip
        https://github.com/immortalwrt/immortalwrt/branches/openwrt-21.02/target/linux/rockchip
        https://github.com/immortalwrt/immortalwrt/branches/openwrt-18.06-k5.4/target/linux/rockchip
        )
        for zx in ${url[@]}; do
          case $zx in
            *trunk*) nn="master-5.15";;
            *21.02*) nn="openwrt-21.02-5.4";;
            *18.06*) nn="openwrt-18.06-k5.4-5.4@5.10";;
          esac
          svn log $zx | awk '/lines$/{printf "%s-%s-%s\n" ,$1,$5,$6}' >xd
          op=$(sed -n '$=' xd); i=0
          for x in `cat xd`; do
            i=$[i+1]; [[ -n $ND ]] && xc=$ND || xc=100; [[ $xc -gt $op ]] && xc=$op
            svn export "-${x%%-*}" $zx immortalwrt/$x-rockchip 1>/dev/null 2>&1 && \
            echo "${nn%-*}分支${zx##*/}总$op个，设置下载$xc个。第$i个$x完成"
            [[ $i = $xc ]] && break
          done
          pushd immortalwrt && \
          tar -zcf ../output/immortalwrt-${zx##*/}-${nn##*-}.tar.gz * --remove-files && popd
        done

    - name: 上传到 Release
      if: steps.feeds.conclusion == 'success' && !cancelled()
      uses: softprops/action-gh-release@master
      with:
        files: output/*
        tag_name: ${{env.STRDATE}}
        token: ${{secrets.GITHUB_TOKEN}}
        name: uboot-rockchip/rockchip/arm-trusted-firmware-rockchip-vendor
        body: coolsnowwolf/immortalwrt-(uboot-rockchip/rockchip/arm-trusted-firmware-rockchip-vendor)存档

  immortalwrt_uboot-rockchip-arm-trusted-firmware-rockchip:
    permissions:
      contents: write
    env:
      ND: ${{github.event.inputs.nd}}
    needs: build_packages
    name: immortalwrt-uboot-rockchip/arm-trusted-firmware-rockchip
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: immortalwrt-uboot-rockchip/arm-trusted-firmware-rockchip
      id: feeds
      run: |
        mkdir output
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        echo "STRDATE=$(date +%Y-%m-%d)" >>$GITHUB_ENV
        url=(
        https://github.com/immortalwrt/immortalwrt/trunk/package/boot/uboot-rockchip
        https://github.com/immortalwrt/immortalwrt/branches/openwrt-21.02/package/boot/uboot-rockchip
        https://github.com/immortalwrt/immortalwrt/branches/openwrt-18.06-k5.4/package/boot/uboot-rockchip
        https://github.com/immortalwrt/immortalwrt/trunk/package/boot/arm-trusted-firmware-rockchip
        https://github.com/immortalwrt/immortalwrt/branches/openwrt-21.02/package/boot/arm-trusted-firmware-rockchip
        https://github.com/immortalwrt/immortalwrt/branches/openwrt-18.06-k5.4/package/boot/arm-trusted-firmware-rockchip
        )
        for zx in ${url[@]}; do
          case $zx in
            *trunk*) nn="master";;
            *21.02*) nn="openwrt-21.02";;
            *18.06*) nn="openwrt-18.06-k5.4";;
          esac
          svn log $zx | awk '/lines$/{printf "%s-%s-%s\n" ,$1,$5,$6}' >xd
          op=$(sed -n '$=' xd); i=0
          for x in `cat xd`; do
            i=$[i+1]; [[ -n $ND ]] && xc=$ND || xc=100; [[ $xc -gt $op ]] && xc=$op
            svn export "-${x%%-*}" $zx immortalwrt/$x-${zx##*/} 1>/dev/null 2>&1 && \
            echo "$nn分支${zx##*/}总$op个，设置下载$xc个。第$i个$x完成"
            [[ $i = $xc ]] && break
          done
          pushd immortalwrt && \
          tar -zcf ../output/immortalwrt-${zx##*/}-$nn.tar.gz * --remove-files && popd
        done
        ls -la output

    - name: 上传到 Release
      if: steps.feeds.conclusion == 'success' && !cancelled()
      uses: softprops/action-gh-release@master
      with:
        files: output/*
        tag_name: ${{env.STRDATE}}
        token: ${{secrets.GITHUB_TOKEN}}
        name: uboot-rockchip/rockchip/arm-trusted-firmware-rockchip-vendor
        body: coolsnowwolf/immortalwrt-(uboot-rockchip/rockchip/arm-trusted-firmware-rockchip-vendor)存档

  coolsnowwolf_rockchip:
    permissions:
      contents: write
    env:
      ND: ${{github.event.inputs.nd}}
    needs: build_packages
    name: coolsnowwolf-rockchip/uboot-rockchip/arm-trusted-firmware-rockchip
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: coolsnowwolf-rockchip/uboot-rockchip/arm-trusted-firmware-rockchip
      id: feeds
      run: |
        mkdir output
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        echo "STRDATE=$(date +%Y-%m-%d)" >>$GITHUB_ENV
        url=(
        https://github.com/coolsnowwolf/lede/trunk/target/linux/rockchip
        https://github.com/coolsnowwolf/lede/trunk/package/boot/uboot-rockchip
        https://github.com/coolsnowwolf/lede/trunk/package/boot/arm-trusted-firmware-rockchip-vendor
        )
        for zx in ${url[@]}; do
          svn log $zx | awk '/lines$/{printf "%s-%s-%s\n" ,$1,$5,$6}' >xd
          op=$(sed -n '$=' xd); i=0
          for x in `cat xd`; do
            i=$[i+1]; [[ -n $ND ]] && xc=$ND || xc=100; [[ $xc -gt $op ]] && xc=$op
            svn export "-${x%%-*}" $zx coolsnowwolf/$x-${zx##*/} 1>/dev/null 2>&1 && \
            echo "${zx##*/}总$op个，设置下载$xc个。第$i个$x完成"
            [[ $i = $xc ]] && break
          done
          pushd coolsnowwolf && \
          tar -zcf ../output/coolsnowwolf-${zx##*/}.tar.gz * --remove-files && popd
        done
        ls -la output

    - name: 上传到 Release
      if: steps.feeds.conclusion == 'success' && !cancelled()
      uses: softprops/action-gh-release@master
      with:
        files: output/*
        tag_name: ${{env.STRDATE}}
        token: ${{secrets.GITHUB_TOKEN}}
        name: uboot-rockchip/rockchip/arm-trusted-firmware-rockchip-vendor
        body: coolsnowwolf/immortalwrt-(uboot-rockchip/rockchip/arm-trusted-firmware-rockchip-vendor)存档

    # - name: 上传到 Release
    #   if: steps.feeds.conclusion == 'success' && !cancelled()
    #   uses: svenstaro/upload-release-action@2.4.1
    #   with:
    #     files: output/*
    #     tag: ${{env.STRDATE}}
    #     overwrite: true
    #     asset_name: uboot-rockchip/rockchip/arm-trusted-firmware-rockchip-vendor
    #     repo_token: ${{secrets.GITHUB_TOKEN}}
